from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(301, 473)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.output_label = QtWidgets.QLabel(self.centralwidget)
        self.output_label.setGeometry(QtCore.QRect(10, 10, 281, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.output_label.setFont(font)
        self.output_label.setMouseTracking(False)
        self.output_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.output_label.setFrameShape(QtWidgets.QFrame.Panel)
        self.output_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.output_label.setLineWidth(2)
        self.output_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.output_label.setObjectName("output_label")
        self.cButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.update_label('C'))
        self.cButton.setGeometry(QtCore.QRect(10, 90, 65, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.cButton.setFont(font)
        self.cButton.setToolTip("")
        self.cButton.setObjectName("cButton")
        self.arrowButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.backspace())
        self.arrowButton.setGeometry(QtCore.QRect(82, 90, 65, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.arrowButton.setFont(font)
        self.arrowButton.setObjectName("arrowButton")
        self.divisionButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.update_label('/'))
        self.divisionButton.setGeometry(QtCore.QRect(153, 90, 65, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.divisionButton.setFont(font)
        self.divisionButton.setObjectName("divisionButton")
        self.eightButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.update_label('8'))
        self.eightButton.setGeometry(QtCore.QRect(82, 160, 65, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.eightButton.setFont(font)
        self.eightButton.setObjectName("eightButton")
        self.nineButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.update_label('9'))
        self.nineButton.setGeometry(QtCore.QRect(153, 160, 65, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.nineButton.setFont(font)
        self.nineButton.setObjectName("nineButton")
        self.sevenButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.update_label('7'))
        self.sevenButton.setGeometry(QtCore.QRect(10, 160, 65, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sevenButton.setFont(font)
        self.sevenButton.setObjectName("sevenButton")
        self.timesButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.update_label('*'))
        self.timesButton.setGeometry(QtCore.QRect(225, 90, 65, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.timesButton.setFont(font)
        self.timesButton.setObjectName("timesButton")
        self.fiveButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.update_label('5'))
        self.fiveButton.setGeometry(QtCore.QRect(82, 230, 65, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.fiveButton.setFont(font)
        self.fiveButton.setObjectName("fiveButton")
        self.sixButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.update_label('6'))
        self.sixButton.setGeometry(QtCore.QRect(153, 230, 65, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sixButton.setFont(font)
        self.sixButton.setObjectName("sixButton")
        self.fourButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.update_label('4'))
        self.fourButton.setGeometry(QtCore.QRect(10, 230, 65, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.fourButton.setFont(font)
        self.fourButton.setObjectName("fourButton")
        self.minusButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.update_label('-'))
        self.minusButton.setGeometry(QtCore.QRect(225, 160, 65, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.minusButton.setFont(font)
        self.minusButton.setObjectName("minusButton")
        self.twoButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.update_label('2'))
        self.twoButton.setGeometry(QtCore.QRect(82, 300, 65, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.twoButton.setFont(font)
        self.twoButton.setObjectName("twoButton")
        self.threeButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.update_label('3'))
        self.threeButton.setGeometry(QtCore.QRect(153, 300, 65, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.threeButton.setFont(font)
        self.threeButton.setObjectName("threeButton")
        self.oneButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.update_label('1'))
        self.oneButton.setGeometry(QtCore.QRect(10, 300, 65, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.oneButton.setFont(font)
        self.oneButton.setObjectName("oneButton")
        self.additionButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.update_label('+'))
        self.additionButton.setGeometry(QtCore.QRect(225, 230, 65, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.additionButton.setFont(font)
        self.additionButton.setObjectName("additionButton")
        self.zeroButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.update_label('0'))
        self.zeroButton.setGeometry(QtCore.QRect(10, 370, 137, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.zeroButton.setFont(font)
        self.zeroButton.setAutoDefault(False)
        self.zeroButton.setObjectName("zeroButton")
        self.decimalButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.period())
        self.decimalButton.setGeometry(QtCore.QRect(153, 370, 65, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.decimalButton.setFont(font)
        self.decimalButton.setObjectName("decimalButton")
        self.equalToButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.evaluate())
        self.equalToButton.setGeometry(QtCore.QRect(225, 300, 65, 131))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.equalToButton.setFont(font)
        self.equalToButton.setObjectName("equalToButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 301, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def evaluate(self):
        screen = self.output_label.text()
        try:
            self.output_label.setText(str(round(eval(screen), 3)))
        except:
            self.output_label.setText('ERROR')
        
    def backspace(self):
        screen = self.output_label.text()
        screen = screen[:-1]
        self.output_label.setText(screen)
        
    def period(self):
        screen = self.output_label.text()
        if '.' not in screen[-1]:
            self.output_label.setText(f'{screen}.')
        
    def update_label(self, key):
        if key == 'C':
            self.output_label.setText('0')
        else:
            if self.output_label.text() == '0':
                self.output_label.setText('')
            self.output_label.setText(f'{self.output_label.text()}{key}')
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.output_label.setText(_translate("MainWindow", "0"))
        self.cButton.setText(_translate("MainWindow", "C"))
        self.cButton.setShortcut(_translate("MainWindow", "Del"))
        self.arrowButton.setText(_translate("MainWindow", "<<"))
        self.arrowButton.setShortcut(_translate("MainWindow", "Backspace"))
        self.divisionButton.setText(_translate("MainWindow", "/"))
        self.divisionButton.setShortcut(_translate("MainWindow", "/"))
        self.eightButton.setText(_translate("MainWindow", "8"))
        self.eightButton.setShortcut(_translate("MainWindow", "8"))
        self.nineButton.setText(_translate("MainWindow", "9"))
        self.nineButton.setShortcut(_translate("MainWindow", "9"))
        self.sevenButton.setText(_translate("MainWindow", "7"))
        self.sevenButton.setShortcut(_translate("MainWindow", "7"))
        self.timesButton.setText(_translate("MainWindow", "x"))
        self.timesButton.setShortcut(_translate("MainWindow", "*"))
        self.fiveButton.setText(_translate("MainWindow", "5"))
        self.fiveButton.setShortcut(_translate("MainWindow", "5"))
        self.sixButton.setText(_translate("MainWindow", "6"))
        self.sixButton.setShortcut(_translate("MainWindow", "6"))
        self.fourButton.setText(_translate("MainWindow", "4"))
        self.fourButton.setShortcut(_translate("MainWindow", "4"))
        self.minusButton.setText(_translate("MainWindow", "-"))
        self.minusButton.setShortcut(_translate("MainWindow", "-"))
        self.twoButton.setText(_translate("MainWindow", "2"))
        self.twoButton.setShortcut(_translate("MainWindow", "2"))
        self.threeButton.setText(_translate("MainWindow", "3"))
        self.threeButton.setShortcut(_translate("MainWindow", "3"))
        self.oneButton.setText(_translate("MainWindow", "1"))
        self.oneButton.setShortcut(_translate("MainWindow", "1"))
        self.additionButton.setText(_translate("MainWindow", "+"))
        self.additionButton.setShortcut(_translate("MainWindow", "+"))
        self.zeroButton.setText(_translate("MainWindow", "0"))
        self.zeroButton.setShortcut(_translate("MainWindow", "0"))
        self.decimalButton.setText(_translate("MainWindow", "."))
        self.decimalButton.setShortcut(_translate("MainWindow", "."))
        self.equalToButton.setText(_translate("MainWindow", "="))
        self.equalToButton.setShortcut(_translate("MainWindow", "Enter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
